#!/usr/bin/env bash
# Web servers act as a software to create and manage the HTML pages

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
